import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  dsaSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Fundamentals',
      items: [{type: 'autogenerated', dirName: 'fundamentals'}],
    },
    {
      type: 'category',
      label: 'Arrays & Strings',
      items: [{type: 'autogenerated', dirName: 'arrays-and-strings'}],
    },
    {
      type: 'category',
      label: 'Linked Lists',
      items: [{type: 'autogenerated', dirName: 'linked-lists'}],
    },
    {
      type: 'category',
      label: 'Stacks & Queues',
      items: [{type: 'autogenerated', dirName: 'stacks-and-queues'}],
    },
    {
      type: 'category',
      label: 'Trees',
      items: [{type: 'autogenerated', dirName: 'trees'}],
    },
    {
      type: 'category',
      label: 'Hash Tables',
      items: [{type: 'autogenerated', dirName: 'hash-tables'}],
    },
    {
      type: 'category',
      label: 'Graphs',
      items: [{type: 'autogenerated', dirName: 'graphs'}],
    },
    {
      type: 'category',
      label: 'Sorting',
      items: [{type: 'autogenerated', dirName: 'sorting'}],
    },
    {
      type: 'category',
      label: 'Searching',
      items: [{type: 'autogenerated', dirName: 'searching'}],
    },
    {
      type: 'category',
      label: 'Dynamic Programming',
      items: [{type: 'autogenerated', dirName: 'dynamic-programming'}],
    },
    {
      type: 'category',
      label: 'Greedy Algorithms',
      items: [{type: 'autogenerated', dirName: 'greedy'}],
    },
    {
      type: 'category',
      label: 'Backtracking',
      items: [{type: 'autogenerated', dirName: 'backtracking'}],
    },
  ],
};

export default sidebars;
